[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = [
  'wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -',
  'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list',
  'apt-get update',
  'apt-get install -y google-chrome-stable',
  'pnpm install'
]

[phases.build] 
cmds = [
  'echo "Chrome location: $(which google-chrome)"',
  'echo "Chrome version: $(google-chrome --version)"',
  'pnpm build'
]

[start]
cmd = 'pnpm start'

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
PUPPETEER_EXECUTABLE_PATH = '/usr/bin/google-chrome'
PUPPETEER_ARGS = '--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --disable-accelerated-2d-canvas --no-first-run --no-zygote --disable-gpu'
