[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm', 'chromium']

[phases.install]
cmds = [
  'pnpm install'
]

[phases.build] 
cmds = [
  'echo "Chromium location: $(which chromium)"',
  'pnpm build'
]

[start]
cmd = 'pnpm start'

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
PUPPETEER_EXECUTABLE_PATH = 'chromium'
