[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']
aptPkgs = ['chromium-browser', 'libnss3', 'libatk1.0-0', 'libatk-bridge2.0-0', 'libcups2', 'libgbm1', 'libasound2t64', 'libpangocairo-1.0-0', 'libxss1', 'libgtk-3-0', 'libxshmfence1', 'libglu1']

[phases.install]
cmds = [
  'pnpm install'
]

[phases.build] 
cmds = [
  'echo "Chromium location: $(which chromium-browser)"',
  'echo "Chromium version: $(chromium-browser --version)"',
  'pnpm build'
]

[start]
cmd = 'pnpm start'

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
PUPPETEER_EXECUTABLE_PATH = '/usr/bin/chromium-browser'
PUPPETEER_ARGS = '--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --disable-accelerated-2d-canvas --no-first-run --no-zygote --disable-gpu'
