[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']
aptPkgs = ['chromium-browser']

[phases.install]
cmds = [
  'pnpm install'
]

[phases.build] 
cmds = [
  'echo "Chromium location: $(which chromium-browser)"',
  'pnpm build'
]

[start]
cmd = 'pnpm start'

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
PUPPETEER_EXECUTABLE_PATH = '/usr/bin/chromium-browser'
