[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']
aptPkgs = ['chromium', 'ca-certificates', 'fonts-liberation', 'libappindicator3-1', 'libasound2t64', 'libatk-bridge2.0-0', 'libdrm2', 'libgtk-3-0', 'libnspr4', 'libnss3', 'libx11-xcb1', 'libxcomposite1', 'libxdamage1', 'libxrandr2', 'xdg-utils']

[phases.install]
cmds = [
  'pnpm install'
]

[phases.build] 
cmds = [
  'echo "Chromium location: $(which chromium)"',
  'echo "Chromium version: $(chromium --version)"',
  'pnpm build'
]

[start]
cmd = 'pnpm start'

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
PUPPETEER_EXECUTABLE_PATH = '/usr/bin/chromium'
PUPPETEER_ARGS = '--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --disable-accelerated-2d-canvas --no-first-run --no-zygote --disable-gpu --disable-extensions'
